name: Mixed inputs test workflow

on:
  workflow_dispatch:
    inputs:
      prNumber:
        required: true
env:
  PR_NUMBER: ${{ github.event.inputs.prNumber }}

jobs:
  find-files:
    name: istio-sanity-test
#    runs-on: cicd-dev
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ' '
          #fileOutput: ' '
          # optional PR number to compare
          prNumber: ${{ github.event.inputs.prNumber }}
          
      - name: 'Find cloud, env and cluster name'
        id: get-cluster-info
        # continue on error so another step can add error output in a comment
        # separate step later will mark this as failed if not successful
        continue-on-error: true
        # "bash {0}" will make all commands run regardless of any one command fails
        shell: bash {0}
        run: |
          all_files="${{ steps.file_changes.outputs.files }}"
          if [[ ! -z "$all_files" ]];
          then
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            if [[ "$(basename $file)" == "main.tf" && -n $(echo "$file" |grep "clusters/") ]]; then
              echo "dir: `dirname $file`"
          done
          fi
